import { createRemoteJWKSet, jwtVerify } from "npm:jose@6";
import { createClient } from "npm:@supabase/supabase-js@2";
const PROJECT_ID=Deno.env.get("FIREBASE_PROJECT_ID")||Deno.env.get("VITE_FIREBASE_PROJECT_ID")||"";
const URL=Deno.env.get("SUPABASE_URL")||"";
const KEYS=JSON.parse(Deno.env.get("SUPABASE_SECRET_KEYS")||"{}");
const db=createClient(URL,KEYS["default"]||"",{auth:{persistSession:false,autoRefreshToken:false}});
const jwks=createRemoteJWKSet(new URL("https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com"));
const POLICY_PATH="config/assessment-remediation-policy.json";
async function uid(auth:string|null){if(!auth?.startsWith("Bearer ")||!PROJECT_ID)throw new Error("Unauthorized");const {payload}=await jwtVerify(auth.slice(7),jwks,{issuer:"https://securetoken.google.com/"+PROJECT_ID,audience:PROJECT_ID});if(typeof payload.sub!=="string")throw new Error("Invalid Firebase token");return payload.sub;}
async function policy(){const {data,error}=await db.storage.from("academia-course-materials").download(POLICY_PATH);if(error||!data)throw new Error("Remediation policy unavailable");const p=JSON.parse(await data.text());const w=p?.weakTopic;if(!Number.isInteger(w?.minimumAnsweredQuestions)||w.minimumAnsweredQuestions<1||!Number.isFinite(w?.accuracyBelowPercent)||w.accuracyBelowPercent<=0||w.accuracyBelowPercent>=100||!Number.isInteger(w?.maximumRecommendations)||w.maximumRecommendations<1)throw new Error("Invalid remediation policy");const seq=Array.isArray(p?.remediationSequence)?p.remediationSequence.filter((x:string)=>typeof x==="string"):[];if(seq.length!==3)throw new Error("Invalid remediation sequence");return {min:w.minimumAnsweredQuestions,threshold:w.accuracyBelowPercent,max:w.maximumRecommendations,sequence:seq};}
const headers=()=>({"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"});
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:headers()});try{const studentId=await uid(req.headers.get("authorization"));const body=await req.json().catch(()=>({}));const assessmentId=typeof body?.assessment_id==="string"?body.assessment_id.trim():null;const p=await policy();const {data,error}=await db.rpc("get_assessment_topic_performance",{p_student_id:studentId,p_assessment_id:assessmentId});if(error)throw new Error("Unable to load topic performance");const rows=Array.isArray(data)?data:[];const recommendations=rows.filter((x:any)=>typeof x?.subject==="string"&&x.subject&&typeof x?.topic==="string"&&x.topic&&Number(x.attempted_questions)>=p.min&&Number(x.accuracy_percent)<p.threshold).sort((a:any,b:any)=>Number(a.accuracy_percent)-Number(b.accuracy_percent)||Number(b.attempted_questions)-Number(a.attempted_questions)).slice(0,p.max).map((x:any,i:number)=>({rank:i+1,priority:Number(x.accuracy_percent)<40?"high":"medium",assessment_id:x.assessment_id,subject:x.subject,topic:x.topic,attempted_questions:Number(x.attempted_questions),accuracy_percent:Number(x.accuracy_percent),remediation_sequence:p.sequence}));return new Response(JSON.stringify({recommendations}),{headers:{...headers(),"Content-Type":"application/json"}});}catch(e){return new Response(JSON.stringify({error:e instanceof Error?e.message:"Request failed"}),{status:400,headers:{...headers(),"Content-Type":"application/json"}});}});
