#!/usr/bin/env node

// VATTAMS ACADEMIA — sitemap generator
// Uses the same public Firebase client-read path as the website.
// Reads published courses only; never writes to Firestore or Supabase.

import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { initializeApp } from 'firebase/app'
import { collection, getDocs, getFirestore, query, where } from 'firebase/firestore'

const SITE_URL = 'https://academia.vattams.net'

const STATIC_ROUTES = [
  { path: '/', changefreq: 'weekly', priority: '1.0' },
  { path: '/courses', changefreq: 'daily', priority: '0.9' },
  { path: '/competitions', changefreq: 'weekly', priority: '0.8' },
  { path: '/competitive-exams', changefreq: 'weekly', priority: '0.9' },
  { path: '/verify-certificate', changefreq: 'monthly', priority: '0.5' },
  { path: '/about', changefreq: 'monthly', priority: '0.6' },
  { path: '/founder', changefreq: 'monthly', priority: '0.5' },
  { path: '/contact', changefreq: 'monthly', priority: '0.5' },
  { path: '/udyam-registration', changefreq: 'yearly', priority: '0.4' },
]

function loadDotEnvLocal() {
  const path = new URL('../.env.local', import.meta.url)
  if (!existsSync(path)) return

  for (const line of readFileSync(path, 'utf8').split('\n')) {
    const match = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)\s*$/)
    if (!match) continue

    const [, key, rawValue] = match
    if (process.env[key] === undefined) {
      process.env[key] = rawValue.replace(/^["']|["']$/g, '')
    }
  }
}

loadDotEnvLocal()

const required = [
  'VITE_FIREBASE_API_KEY',
  'VITE_FIREBASE_AUTH_DOMAIN',
  'VITE_FIREBASE_PROJECT_ID',
  'VITE_FIREBASE_MESSAGING_SENDER_ID',
  'VITE_FIREBASE_APP_ID',
]

const missing = required.filter((name) => !process.env[name])

if (missing.length > 0) {
  console.error(`Missing Firebase environment variable(s): ${missing.join(', ')}`)
  process.exit(1)
}

const app = initializeApp({
  apiKey: process.env.VITE_FIREBASE_API_KEY,
  authDomain: process.env.VITE_FIREBASE_AUTH_DOMAIN,
  projectId: process.env.VITE_FIREBASE_PROJECT_ID,
  messagingSenderId: process.env.VITE_FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.VITE_FIREBASE_APP_ID,
})

const db = getFirestore(app)

function escapeXml(value) {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;')
}

function urlEntry({ path, changefreq, priority }) {
  return [
    '  <url>',
    `    <loc>${escapeXml(SITE_URL + path)}</loc>`,
    `    <changefreq>${changefreq}</changefreq>`,
    `    <priority>${priority}</priority>`,
    '  </url>',
  ].join('\n')
}

async function main() {
  const coursesQuery = query(
    collection(db, 'courses'),
    where('is_published', '==', true),
  )

  const snapshot = await getDocs(coursesQuery)

  const courseRoutes = snapshot.docs
    .map((doc) => doc.data())
     .filter((course) => course.slug)
    .map((course) => ({
      path: `/courses/${course.slug}`,
      changefreq: 'weekly',
      priority: '0.8',
    }))
    .sort((a, b) => a.path.localeCompare(b.path))

  const entries = [...STATIC_ROUTES, ...courseRoutes]
    .map(urlEntry)
    .join('\n')

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!--
  VATTAMS ACADEMIA — sitemap.xml
  Generated by scripts/generate-sitemap.mjs
-->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries}
</urlset>
`

  const outPath = new URL('../public/sitemap.xml', import.meta.url)
  writeFileSync(outPath, xml, 'utf8')

  console.log(
    `Wrote ${STATIC_ROUTES.length} static + ${courseRoutes.length} published course URLs to public/sitemap.xml`,
  )
}

main().catch((err) => {
  console.error('Failed to generate sitemap:', err)
  process.exit(1)
})
