#!/usr/bin/env node
// =====================================================================
// VATTAMS ACADEMIA — sitemap generator (Firestore, NOT Supabase)
//
// Regenerates public/sitemap.xml: the static public routes below, plus
// one <url> per published, non-competition course from the `courses`
// Firestore collection (is_published: true — the same collection and
// flag Courses.tsx / CourseDetail.tsx already read).
//
// STATIC_ROUTES is hand-maintained against src/App.tsx's actual <Route>
// list. It intentionally excludes /verify and /competitive-exams —
// both are duplicate routes for /verify-certificate and /competitions
// (same component, two paths) and carry a canonical link back to the
// canonical path instead (see useSeo() calls in VerifyCertificate.tsx /
// Competitions.tsx) — including the duplicate path here would submit
// the same content twice.
//
// Same firebase-admin credential pattern as scripts/seed-catalog.mjs —
// see that script's header for full setup:
//   export GOOGLE_APPLICATION_CREDENTIALS=/absolute/path/to/key.json
//   node scripts/generate-sitemap.mjs
//
// Read-only: only reads the `courses` collection, never writes to
// Firestore or to Supabase. Only writes to public/sitemap.xml on disk.
// =====================================================================

import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { initializeApp, applicationDefault } from 'firebase-admin/app'
import { getFirestore } from 'firebase-admin/firestore'

const SITE_URL = 'https://academia.vattams.net'

const STATIC_ROUTES = [
  { path: '/', changefreq: 'weekly', priority: '1.0' },
  { path: '/courses', changefreq: 'daily', priority: '0.9' },
  { path: '/competitions', changefreq: 'weekly', priority: '0.6' },
  { path: '/verify-certificate', changefreq: 'monthly', priority: '0.5' },
  { path: '/about', changefreq: 'monthly', priority: '0.6' },
  { path: '/founder', changefreq: 'monthly', priority: '0.5' },
  { path: '/contact', changefreq: 'monthly', priority: '0.5' },
  { path: '/privacy-policy', changefreq: 'yearly', priority: '0.2' },
  { path: '/terms', changefreq: 'yearly', priority: '0.2' },
  { path: '/refund-policy', changefreq: 'yearly', priority: '0.2' },
  { path: '/student/register', changefreq: 'monthly', priority: '0.6' },
  { path: '/tutor/register', changefreq: 'monthly', priority: '0.6' },
]

function loadDotEnvLocal() {
  const path = new URL('../.env.local', import.meta.url)
  if (!existsSync(path)) return
  for (const line of readFileSync(path, 'utf8').split('\n')) {
    const m = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)\s*$/)
    if (!m) continue
    const [, key, rawValue] = m
    if (process.env[key] === undefined) {
      process.env[key] = rawValue.replace(/^["']|["']$/g, '')
    }
  }
}

loadDotEnvLocal()

const projectId = process.env.FIREBASE_PROJECT_ID || process.env.VITE_FIREBASE_PROJECT_ID
if (!projectId) {
  console.error(
    'Missing project id. Set VITE_FIREBASE_PROJECT_ID in .env.local (same value the app already uses) ' +
      'or FIREBASE_PROJECT_ID as an env var.'
  )
  process.exit(1)
}

const credential = process.env.GOOGLE_APPLICATION_CREDENTIALS ? applicationDefault() : null
if (!credential) {
  console.error(
    'Missing GOOGLE_APPLICATION_CREDENTIALS. Generate a service account key from ' +
      'Firebase Console -> Project settings -> Service accounts, then:\n' +
      '  export GOOGLE_APPLICATION_CREDENTIALS=/absolute/path/to/key.json'
  )
  process.exit(1)
}

initializeApp({ credential, projectId })
const db = getFirestore()

function escapeXml(value) {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;')
}

function urlEntry({ path, changefreq, priority }) {
  return [
    '  <url>',
    `    <loc>${escapeXml(SITE_URL + path)}</loc>`,
    `    <changefreq>${changefreq}</changefreq>`,
    `    <priority>${priority}</priority>`,
    '  </url>',
  ].join('\n')
}

async function main() {
  const snapshot = await db.collection('courses').where('is_published', '==', true).get()

  const courseRoutes = snapshot.docs
    .map((doc) => doc.data())
    .filter((course) => !course.is_competition && course.slug)
    .map((course) => ({
      path: `/courses/${course.slug}`,
      changefreq: 'weekly',
      priority: '0.8',
    }))

  const entries = [...STATIC_ROUTES, ...courseRoutes].map(urlEntry).join('\n')

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!--
  VATTAMS ACADEMIA — sitemap.xml
  Generated by scripts/generate-sitemap.mjs — do not hand-edit course
  URLs here; re-run the script instead. Static routes can be hand-edited
  (also update STATIC_ROUTES in the script so the next run doesn't drop
  the change).
-->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries}
</urlset>
`

  const outPath = new URL('../public/sitemap.xml', import.meta.url)
  writeFileSync(outPath, xml, 'utf8')

  console.log(`Wrote ${STATIC_ROUTES.length} static + ${courseRoutes.length} course URLs to public/sitemap.xml`)
}

main().catch((err) => {
  console.error('Failed to generate sitemap:', err)
  process.exit(1)
})
